--Reg-Contries
CREATE TABLE REGIONS ( 
region_id      int,
region_name   VARCHAR(15) 
);
SELECT * FROM REGIONS;


ALTER TABLE REGIONS
   ADD CONSTRAINT reg_id_pk
   PRIMARY KEY (region_id);
   
-----------------------------------------

CREATE TABLE COUNTRIES ( 
COUNTRY_ID      VARCHAR(2),
COUNTRY_NAME    VARCHAR(40), 
REGION_ID       int
);

SELECT * FROM COUNTRIES;
 
ALTER TABLE COUNTRIES
ADD  CONSTRAINT COUNTR_REG_FK
FOREIGN KEY (REGION_ID)
REFERENCES REGIONS(REGION_ID); 

-------------------------------------------

CREATE TABLE LOCATIONS ( 
LOCATION_ID    int not NULL , 
STREET_ADDRESS VARCHAR(40), 
POSTAL_CODE    VARCHAR(12),
CITY       VARCHAR(30),
STATE_PROVINCE VARCHAR(25), 
COUNTRY_ID     VARCHAR(2)
);

SELECT * FROM LOCATIONS;

ALTER TABLE LOCATIONS
ADD  CONSTRAINT LOC_ID_PK
PRIMARY KEY (LOCATION_ID),
FOREIGN KEY (COUNTRY_ID)
REFERENCES COUNTRIES(COUNTRY_ID); 